### ISSUE TITLE
Old forms mudule used?

### ISSUE THREAD

**Issue by squio** [Gajotres/Ionic2FormValidation#2]
Using ionic 2 beta 11 I  get the following warning:

`*It looks like you're using the old forms module. This will be opt-in in the next RC, and
      will eventually be removed in favor of the new forms module. For more information, see:
      https://docs.google.com/document/u/1/d/1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/pub`

Followed by a couple pf exceptions.

**Comment by Gajotres** [comment]
Demo project has been updated to Ionic 2.2.1 version
